[features]
seeds = false
skip-lint = false
[programs.localnet]
sample_app = "2j3BgHSJgXpvPne1JUkLaZ7W5Q1LmcF4RomqMg121mvf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/bare/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
